title: "Effectif Development"
subtitle: "Graham Ashton on Ruby, Python, JavaScript and Web Development."
description: "Notes on the use of dynamic scripting languages for agile web development, covering Ruby on Rails, JavaScript and version control with git. Maintained by Graham Ashton."
keywords: "Graham Ashton, ruby, javascript, web, git"

author:
  name: Graham Ashton
  uri: http://effectif.com
  email: graham@effectif.com

theme: slate

disqus_short_name: effectif

cache: false
content: content

production:
  cache: true
  content: /var/apps/nesta/shared/content
  google_analytics_code: "UA-4055128-1"
