title: "Effectif Development"
subtitle: "Graham Ashton on Ruby, Python, JavaScript and Web Development"

author:
  name: Graham Ashton
  uri: http://effectif.com
  email: graham@effectif.com

# theme: slate

disqus_short_name: effectif

cache: false
content: content

production:
  cache: true
  content: /var/apps/effectif.com/shared/content
  google_analytics_code: "UA-4055128-1"
